# Generated by Django 5.0.4 on 2025-03-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistmodel',
            name='status',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
